# Generated by Django 4.0.4 on 2022-05-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptablero', '0002_alter_ventas_rama'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ventas',
        ),
    ]
