# Generated by Django 4.0.4 on 2022-05-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rfc', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
    ]
