# Generated by Django 4.0.4 on 2022-05-08 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppersonal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
