# Generated by Django 4.0.4 on 2022-05-08 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apppersonal', '0004_tipoempleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='tipo_empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apppersonal.tipoempleado'),
        ),
    ]
