# Generated by Django 4.0.4 on 2022-05-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppersonal', '0005_persona_tipo_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='es_empleado',
            field=models.BooleanField(default=False),
        ),
    ]
