# Generated by Django 4.0.4 on 2022-05-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppersonal', '0006_persona_es_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
