# Generated by Django 4.0.4 on 2022-05-08 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppersonal', '0007_persona_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 22, 9, 55, 902861)),
        ),
    ]
