# Generated by Django 4.0.4 on 2022-05-08 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppersonal', '0008_persona_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='sueldo',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 22, 11, 9, 469358)),
        ),
    ]
