# Generated by Django 4.0.4 on 2022-05-08 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppersonal', '0010_persona_altura_alter_persona_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='cintura',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 22, 13, 30, 704540)),
        ),
    ]
