# Generated by Django 4.0.4 on 2022-05-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_factura', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('rama', models.CharField(max_length=100)),
                ('ciuda', models.CharField(max_length=100)),
                ('tipo_cliente', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('linea_de_producto', models.CharField(max_length=100)),
                ('precio_por_unidad', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cantida', models.IntegerField(default=0)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
                ('pago', models.CharField(max_length=100)),
                ('costo_de_bienes', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('porcentaje_de_magen_bruto', models.FloatField(null=True)),
                ('ingresos_brutos', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('clasificacion', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
