# Generated by Django 4.0.4 on 2022-05-14 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptablero', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='ciuda',
            new_name='ciudad',
        ),
    ]
